'''used to import files within module'''

from .get_random_info import get_random_info
from .info_string_generator.get_random_pokemon_ability_string import get_random_pokemon_ability_string as get_random_pokemon_ability_info
from .info_string_generator.get_random_pokemon_evolution_string import get_random_pokemon_evolution_string as get_random_pokemon_evolution_info
from .info_string_generator.get_random_pokemon_generation_introduced_string import get_random_pokemon_generation_introduced_string as get_random_pokemon_generation_introduced_info
from .info_string_generator.get_random_pokemon_height_string import get_random_pokemon_height_string as get_random_pokemon_height_info
from .info_string_generator.get_random_pokemon_highest_stat_string import get_random_pokemon_highest_stat_string as get_random_pokemon_highest_stat_info
from .info_string_generator.get_random_pokemon_lowest_stat_string import get_random_pokemon_lowest_stat_string as get_random_pokemon_lowest_stat_info
from .info_string_generator.get_random_pokemon_type_string import get_random_pokemon_type_string as get_random_pokemon_type_info
from .info_string_generator.get_random_pokemon_type_weakness_or_resistance_string import get_random_pokemon_type_weakness_or_resistance_string as get_random_pokemon_type_weakness_or_resistance_info
from .info_string_generator.get_random_pokemon_weight_string import get_random_pokemon_weight_string as get_random_pokemon_weight_info
from .pre_cache_all_used_endpoints import pre_cache_all_used_endpoints
