'''used to import files within module'''

from .get_random_pokemon_ability_string import get_random_pokemon_ability_string
from .get_random_pokemon_evolution_string import get_random_pokemon_evolution_string
from .get_random_pokemon_generation_introduced_string import get_random_pokemon_generation_introduced_string
from .get_random_pokemon_height_string import get_random_pokemon_height_string
from .get_random_pokemon_highest_stat_string import get_random_pokemon_highest_stat_string
from .get_random_pokemon_lowest_stat_string import get_random_pokemon_lowest_stat_string
from .get_random_pokemon_type_string import get_random_pokemon_type_string
from .get_random_pokemon_type_weekness_or_resistance_string import get_random_pokemon_type_weekness_or_resistance_string
from .get_random_pokemon_weight_string import get_random_pokemon_weight_string
